# Generated by Django 5.1.7 on 2025-03-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF')], default='pdf', max_length=20),
        ),
    ]
